var camins = [
	  [['tram_01_1'],cami_01_1,["#383838"],['3,7'],["El Cami al Baix Ebre, Matarranya, Terra Alta, Ribera d'Ebre i Priorat"+'</br>150 km'+'</br><a href="http://elcami.cat/node/2631">enllaç pàgina</a>']],
	  [['tram_01_2'],cami_01_2,["orange"],['0,0'],["El Cami al Baix Ebre, Matarranya, Terra Alta, Ribera d'Ebre i Priorat"+'</br>150 km'+'</br><a href="http://elcami.cat/node/2631">enllaç pàgina</a>']],
	  [['tram_01_3'],cami_01_3,["#383838"],['3,7'],["El Cami al Baix Ebre, Matarranya, Terra Alta, Ribera d'Ebre i Priorat"+'</br>150 km'+'</br><a href="http://elcami.cat/node/2631">enllaç pàgina</a>']],
	  [['tram_01_4'],cami_01_4,["orange"],['0,0'],["El Cami al Baix Ebre, Matarranya, Terra Alta, Ribera d'Ebre i Priorat"+'</br>150 km'+'</br><a href="http://elcami.cat/node/2631">enllaç pàgina</a>']],
	  [['tram_03'],cami_03,["#383838"],['3,7'],["El Camí al Tarragonès, Penedès i Anoia"+'</br><a href="http://elcami.cat/tram/tarragon%C3%A8s-pened%C3%A8s-anoia">enllaç pàgina</a>']],
	  [['tram_04_1'],cami_04_1,["#383838"],['3,7'],["El Cami a l'Anoia, Bages i Osona"+'</br>130 km']],
	  [['tram_04_2'],cami_04_2,["orange"],['0,0'],["El Cami a l'Anoia, Bages i Osona"+'</br>130 km']],
	  [['tram_04_3'],cami_04_3,["#383838"],['3,7'],["El Cami a l'Anoia, Bages i Osona"+'</br>130 km']],
	  [['tram_5_1'],cami_5_1,["#383838"],['3,7'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_2'],cami_5_2,["red"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_3'],cami_5_3,["orange"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_4'],cami_5_4,["red"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_5'],cami_5_5,["orange"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_6'],cami_5_6,["green"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_7'],cami_5_7,["orange"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_5_8'],cami_5_8,["red"],['0,0'],["El Camí al Vallès Oriental i Maresme"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_06'],cami_06,["red"],['0,0'],["El Camí al Montseny"+'</br>91 km'+'</br><a href="http://elcami.cat/tram/montseny-vall%C3%A8s-oriental-selva-osona">enllaç pàgina</a>']],
	  [['tram_07_1'],cami_07_1,["orange"],['0,0'],["El Camí a Osona, La Selvà i Gironès"]],
	  [['tram_07_2'],cami_07_2,["#383838"],['3,7'],["El Camí a Osona, La Selvà i Gironès"]],
	  [['tram_07_3'],cami_07_3,["#383838"],['3,7'],["El Camí a Osona, La Selvà i Gironès"]],
	  [['tram_08_1'],cami_08_1,["green"],['0,0'],["El Camí al Gironès, l'Empordà i el Rosselló"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/giron%C3%A8s-empord%C3%A0-rossell%C3%B3">enllaç pàgina</a>']],
	  [['tram_08_2'],cami_08_2,["orange"],['0,0'],["El Camí al Gironès, l'Empordà i el Rosselló"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/giron%C3%A8s-empord%C3%A0-rossell%C3%B3">enllaç pàgina</a>']],
	  [['tram_08_3'],cami_08_3,["green"],['0,0'],["El Camí al Gironès, l'Empordà i el Rosselló"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/giron%C3%A8s-empord%C3%A0-rossell%C3%B3">enllaç pàgina</a>']],
	  [['tram_08_4'],cami_08_4,["orange"],['0,0'],["El Camí al Gironès, l'Empordà i el Rosselló"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/giron%C3%A8s-empord%C3%A0-rossell%C3%B3">enllaç pàgina</a>']],
	  [['tram_08_5'],cami_08_5,["green"],['0,0'],["El Camí al Gironès, l'Empordà i el Rosselló"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/giron%C3%A8s-empord%C3%A0-rossell%C3%B3">enllaç pàgina</a>']],
	  [['tram_09_1'],cami_09_1,["#383838"],['3,7'],["El Camí al Rosselló, al Conflent i al Vallespir"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/rossell%C3%B3-conflent-vallespir">enllaç pàgina</a>']],
	  [['tram_09_2'],cami_09_2,["orange"],['0,0'],["El Camí al Rosselló, al Conflent i al Vallespir"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/rossell%C3%B3-conflent-vallespir">enllaç pàgina</a>']],
	  [['tram_09_3'],cami_09_3,["#383838"],['3,7'],["El Camí al Rosselló, al Conflent i al Vallespir"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/rossell%C3%B3-conflent-vallespir">enllaç pàgina</a>']],
	  [['tram_10_1'],cami_10_1,["orange"],['0,0'],["El Camí al Vallespir, l'Alta Garrotxa i el Pla de l'Estany"+'</br>35 km'+'</br><a href="http://elcami.cat/tram/vallespir-pla-estany">enllaç pàgina</a>']],
	  [['tram_10_2'],cami_10_2,["red"],['0,0'],["El Camí al Vallespir, l'Alta Garrotxa i el Pla de l'Estany"+'</br>35 km'+'</br><a href="http://elcami.cat/tram/vallespir-pla-estany">enllaç pàgina</a>']],
	  [['tram_12'],cami_12,["red"],['0,0'],["El Camí a la Garrotxa i al Ripollès"+'</br>83 km'+'</br><a href="http://elcami.cat/tram/garrotxa-ripoll%C3%A8s">enllaç pàgina</a>']],
	  [['tram_13'],cami_13,["yellow"],['0,0'],["Brancal de l'Alta Garrotxa"+'</br>70.58 km'+'</br><a href="http://elcami.cat/tram/alta-garrotxa-ripoll%C3%A8s">enllaç pàgina</a>']],
	  [['tram_14'],cami_14,["yellow"],['0,0'],["Brancal de Vidabona"+'</br>34.67 km'+'</br><a href="http://elcami.cat/tram/vidabona">enllaç pàgina</a>']],
	  [['tram_15'],cami_15,["yellow"],['0,0'],["Brancal de Núria i Montgrony"+'</br>56.9 km'+'</br><a href="http://elcami.cat/tram/n%C3%BAria-montgrony">enllaç pàgina</a>']],
	  [['tram_16'],cami_16,["orange"],['0,0'],["El Camí al Berguedà, la Cerdanya i al Capcir"+'</br>195 km'+'</br><a href="http://elcami.cat/tram/bergued%C3%A0-cerdanya-capcir">enllaç pàgina</a>']],
	  [['tram_17'],cami_17,["red"],['0,0'],["El Camí al Capcir, Andorra i l'Alt Urgell"+'</br>162 km'+'</br><a href="http://elcami.cat/tram/capcir-andorra-alt-urgell">enllaç pàgina</a>']],
	  [['tram_18'],cami_18,["orange"],['0,0'],["El Camí a l'Alt Urgell, Pallars Sobirà i Ribagorça"+'</br>220 km'+'</br><a href="http://elcami.cat/tram/alt-urgell-pallars-sobir%C3%A0-ribagor%C3%A7a">enllaç pàgina</a>']],
	  [['tram_19'],cami_19,["green"],['0,0'],["Brancal de la Val d'Aran"+'</br>220 km'+'</br>']],
	  [['tram_20'],cami_20,["red"],['0,0'],["El Camí a la Ribagorça, Pallars Jussà i Noguera"+'</br>164 km'+'</br><a href="http://elcami.cat/tram/ribagor%C3%A7a-pallars-juss%C3%A0-noguera">enllaç pàgina</a>']],
	  [['tram_21'],cami_21,["#383838"],['3,7'],["El Camí a la Noguera, Llitera, Baix Cinca i Segrià"+'</br>125 km'+'</br>']],
	  [['tram_23'],cami_23,["green"],['0,0'],["Brancal de la Segarra històrica"+'</br>110 km'+'</br><a href="http://www.elcami.cat/tram/segarra-historica">enllaç pàgina</a>']],
	  [['tram_24_1'],cami_24_1,["#383838"],['3,7'],["El Camí a la Segarra, el Solsonès, el Bages i el Vallès Occidental"]],
	  [['tram_24_2'],cami_24_2,["orange"],['0,0'],["El Camí a la Segarra, el Solsonès, el Bages i el Vallès Occidental"]],
	  [['tram_26'],cami_26,["#383838"],['3,7'],["El Camí a l'Alguer i Menorca"+'</br>140 km'+'</br><a href="http://elcami.cat/tram/menorca">enllaç pàgina</a>']],
	  [['tram_27_1'],cami_27_1,["#383838"],['3,7'],["El Camí a Mallorca: de la Serra de Tramuntana a Migjorn"+'</br>155 km'+'</br><a href="http://elcami.cat/tram/mallorca-tramuntana-nord-llevant">enllaç pàgina</a>']],
	  [['tram_27_2'],cami_27_2,["orange"],['0,0'],["El Camí a Mallorca: de la Serra de Tramuntana a Migjorn"+'</br>155 km'+'</br><a href="http://elcami.cat/tram/mallorca-tramuntana-nord-llevant">enllaç pàgina</a>']],
	  [['tram_27_3'],cami_27_3,["#383838"],['3,7'],["El Camí a Mallorca: de la Serra de Tramuntana a Migjorn"+'</br>155 km'+'</br><a href="http://elcami.cat/tram/mallorca-tramuntana-nord-llevant">enllaç pàgina</a>']],
	  [['tram_28_1'],cami_28_1,["orange"],['0,0'],["El Camí a Mallorca: de Migjorn a Palma"+'</br>191 km'+'</br><a href="http://elcami.cat/tram/mallorca-raiguer-migjorn-tramuntana-palma">enllaç pàgina</a>']],
	  [['tram_28_2'],cami_28_2,["red"],['0,0'],["El Camí a Mallorca: de Migjorn a Palma"]],
	  [['tram_29'],cami_29,["orange"],['0,0'],["El Camí a les Pitiüses"+'</br>169 km'+'</br><a href="http://elcami.cat/tram/eivissa-formentera">enllaç pàgina</a>']],
	  [['tram_30_1'],cami_30_1,["red"],['0,0'],["El Camí a La Marina"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/marina-alta-marina-baixa">enllaç pàgina</a>']],
	  [['tram_30_2'],cami_30_2,["#383838"],['3,7'],["El Camí a La Marina"+'</br>104 km'+'</br><a href="http://elcami.cat/tram/marina-alta-marina-baixa">enllaç pàgina</a>']],
	  [['tram_31'],cami_31,["#383838"],['3,7'],["El Camí a la Marina i l'Alacantí"]],
	  [['tram_32_1'],cami_32_1,["orange"],['0,0'],["El Camí al Carxe i Vinalopó"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/baix-vinalop%C3%B3-valls-vinalop%C3%B3-carxe">enllaç pàgina</a>']],
	  [['tram_32_2'],cami_32_2,["#383838"],['3,7'],["El Camí al Carxe i Vinalopó"+'</br>205 km'+'</br><a href="http://elcami.cat/tram/baix-vinalop%C3%B3-valls-vinalop%C3%B3-carxe">enllaç pàgina</a>']],
	  [['tram_33_1'],cami_33_1,["#383838"],['3,7'],["El Camí a Mariola"+'</br>94 km'+'</br><a href="http://www.elcami.cat/tram/mariola-alcoia-comtat-vall-albaida">enllaç pàgina</a>']],
	  [['tram_33_2'],cami_33_2,["orange"],['0,0'],["El Camí a Mariola"+'</br>94 km'+'</br><a href="http://www.elcami.cat/tram/mariola-alcoia-comtat-vall-albaida">enllaç pàgina</a>']],
	  [['tram_33_3'],cami_33_3,["#383838"],['3,7'],["El Camí a Mariola"+'</br>94 km'+'</br><a href="http://www.elcami.cat/tram/mariola-alcoia-comtat-vall-albaida">enllaç pàgina</a>']],
	  [['tram_34_1'],cami_34_1,["#383838"],['3,7'],["El Camí a la Vall d’Albaida, Safor i Costera"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/vall-albaida-safor-valldigna-costera">enllaç pàgina</a>']],
	  [['tram_34_2'],cami_34_2,["orange"],['0,0'],["El Camí a la Vall d’Albaida, Safor i Costera"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/vall-albaida-safor-valldigna-costera">enllaç pàgina</a>']],
	  [['tram_34_3'],cami_34_3,["#383838"],['3,7'],["El Camí a la Vall d’Albaida, Safor i Costera"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/vall-albaida-safor-valldigna-costera">enllaç pàgina</a>']],
	  [['tram_35_1'],cami_35_1,["#383838"],['3,7'],["El Camí a la Costera, Safor, Ribera, Horta"+'</br>107 km'+'</br><a href="http://elcami.cat/tram/costera-ribera-horta">enllaç pàgina</a>']],
	  [['tram_35_2'],cami_35_2,["orange"],['0,0'],["El Camí a la Costera, Safor, Ribera, Horta"+'</br>107 km'+'</br><a href="http://elcami.cat/tram/costera-ribera-horta">enllaç pàgina</a>']],
	  [['tram_35_3'],cami_35_3,["#383838"],['3,7'],["El Camí a la Costera, Safor, Ribera, Horta"+'</br>107 km'+'</br><a href="http://elcami.cat/tram/costera-ribera-horta">enllaç pàgina</a>']],
	  [['tram_36_1'],cami_36_1,["green"],['0,0'],["El Camí a Túria-Calderona"+'</br>100 km']],
	  [['tram_36_2'],cami_36_2,["green"],['0,0'],["El Camí a Túria-Calderona"+'</br>100 km']],
	  [['tram_36_3'],cami_36_3,["green"],['0,0'],["El Camí a Túria-Calderona"+'</br>100 km']],
	  [['tram_37_1'],cami_37_1,["orange"],['0,0'],["El Camí al Morvedre, Vall de Segó i La Plana"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/camp-morvedre-vall-seg%C3%B3-plana">enllaç pàgina</a>']],
	  [['tram_37_2'],cami_37_2,["orange"],['0,0'],["El Camí al Morvedre, Vall de Segó i La Plana"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/camp-morvedre-vall-seg%C3%B3-plana">enllaç pàgina</a>']],
	  [['tram_37_3'],cami_37_3,["orange"],['0,0'],["El Camí al Morvedre, Vall de Segó i La Plana"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/camp-morvedre-vall-seg%C3%B3-plana">enllaç pàgina</a>']],
	  [['tram_37_4'],cami_37_4,["orange"],['0,0'],["El Camí al Morvedre, Vall de Segó i La Plana"+'</br>120 km'+'</br><a href="http://elcami.cat/tram/camp-morvedre-vall-seg%C3%B3-plana">enllaç pàgina</a>']],
	  [['tram_38'],cami_38,["red"],['0,0'],["El Camí al Penyagolosa"+'</br>120 km'+'</br><a href="http://www.elcami.cat/tram/penyagolosa">enllaç pàgina</a>']],
	  [['tram_39'],cami_39,["red"],['0,0'],["El Camí a l'Alt Maestrat i Els Ports"+'</br>120 km'+'</br><a href="http://www.elcami.cat/tram/alt-maestrat-ports-senyalitzat">enllaç pàgina</a>']],
	  [['tram_40_1'],cami_40_1,["orange"],['0,0'],["El Camí del Sènia a l'Ebre"+'</br>205 km'+'</br><a href="http://www.elcami.cat/tram/ports-baix-maestrat-montsi%25C3%25A0-baix-ebre-proc%25C3%25A9">enllaç pàgina</a>']],
	  [['tram_40_2'],cami_40_2,["green"],['0,0'],["El Camí del Sènia a l'Ebre"+'</br>205 km'+'</br><a href="http://www.elcami.cat/tram/ports-baix-maestrat-montsi%25C3%25A0-baix-ebre-proc%25C3%25A9">enllaç pàgina</a>']],
	  [['tram_41'],cami_41,["green"],['0,0'],["Brancal de Menorca"+'</br>51 km'+'</br><a href="http://elcami.cat/tram/menorca">enllaç pàgina</a>']],	
	  [['tram_42'],cami_42,["yellow"],['0,0'],["Brancal del Pla de Llerona"+'</br>9 km'+'</br><a href="http://elcami.cat/tram/vall%C3%A8s-oriental-maresme">enllaç pàgina</a>']],
	  [['tram_43'],cami_43,["yellow"],['0,0'],["Brancal de la Barceloneta"+'</br>9.4 km'+'</br><a href="http://elcami.cat/tram/vallesoccidental-baixllobregat-barcelones">enllaç pàgina</a>']],
	  [['tram_44'],cami_44,["yellow"],['0,0'],["Brancal de Sant Martí"+'</br>11.8 km'+'</br><a href="http://elcami.cat/tram/vallesoccidental-baixllobregat-barcelones">enllaç pàgina</a>']],
	  [['tram_45'],cami_45,["yellow"],['0,0'],["Brancal de Nou Barris"+'</br>15.3 km'+'</br><a href="http://elcami.cat/tram/vallesoccidental-baixllobregat-barcelones">enllaç pàgina</a>']],
	  [['tram_46'],cami_46,["yellow"],['0,0'],["Brancal de Collserola"+'</br>15.7 km'+'</br><a href="http://elcami.cat/tram/vallesoccidental-baixllobregat-barcelones">enllaç pàgina</a>']],
	  [['tram_47'],cami_47,["yellow"],['0,0'],["Brancal de les Corts"+'</br>11.5 km'+'</br><a href="http://elcami.cat/tram/vallesoccidental-baixllobregat-barcelones">enllaç pàgina</a>']],
	  [['tram_48'],cami_48,["yellow"],['0,0'],["Branal de Sants"+'</br>24 km'+'</br><a href="http://elcami.cat/tram/vallesoccidental-baixllobregat-barcelones">enllaç pàgina</a>']],

	];

